/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExperienceLevel = IDL.Variant({
  'junior' : IDL.Null,
  'midLevel' : IDL.Null,
  'senior' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'experienceLevel' : ExperienceLevel,
  'verified' : IDL.Bool,
  'jobRole' : IDL.Text,
  'name' : IDL.Text,
  'currentCity' : IDL.Text,
  'preferredCity' : IDL.Text,
  'companyName' : IDL.Text,
  'salaryRange' : IDL.Text,
});
export const SwapRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const SwapRequest = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Principal,
  'status' : SwapRequestStatus,
  'from' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const Message = IDL.Record({
  'content' : IDL.Text,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptSwapRequest' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'findMatches' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAllConversations' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAllData' : IDL.Func(
      [],
      [
        IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile)),
        IDL.Vec(SwapRequest),
        IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Principal, IDL.Vec(Message))),
      ],
      ['query'],
    ),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessagesWith' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getSwapRequests' : IDL.Func([], [IDL.Vec(SwapRequest)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectSwapRequest' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'sendSwapRequest' : IDL.Func([IDL.Principal], [], []),
  'verifyProfile' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExperienceLevel = IDL.Variant({
    'junior' : IDL.Null,
    'midLevel' : IDL.Null,
    'senior' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'experienceLevel' : ExperienceLevel,
    'verified' : IDL.Bool,
    'jobRole' : IDL.Text,
    'name' : IDL.Text,
    'currentCity' : IDL.Text,
    'preferredCity' : IDL.Text,
    'companyName' : IDL.Text,
    'salaryRange' : IDL.Text,
  });
  const SwapRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const SwapRequest = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Principal,
    'status' : SwapRequestStatus,
    'from' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const Message = IDL.Record({
    'content' : IDL.Text,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptSwapRequest' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'findMatches' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getAllConversations' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getAllData' : IDL.Func(
        [],
        [
          IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile)),
          IDL.Vec(SwapRequest),
          IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Principal, IDL.Vec(Message))),
        ],
        ['query'],
      ),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessagesWith' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getSwapRequests' : IDL.Func([], [IDL.Vec(SwapRequest)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectSwapRequest' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'sendSwapRequest' : IDL.Func([IDL.Principal], [], []),
    'verifyProfile' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };