/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExperienceLevel = { 'junior' : null } |
  { 'midLevel' : null } |
  { 'senior' : null };
export interface Message {
  'content' : string,
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : bigint,
}
export interface SwapRequest {
  'id' : bigint,
  'to' : Principal,
  'status' : SwapRequestStatus,
  'from' : Principal,
  'timestamp' : bigint,
}
export type SwapRequestStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface UserProfile {
  'experienceLevel' : ExperienceLevel,
  'verified' : boolean,
  'jobRole' : string,
  'name' : string,
  'currentCity' : string,
  'preferredCity' : string,
  'companyName' : string,
  'salaryRange' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptSwapRequest' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'findMatches' : ActorMethod<[], Array<Principal>>,
  'getAllConversations' : ActorMethod<[], Array<Principal>>,
  'getAllData' : ActorMethod<
    [],
    [
      Array<[Principal, UserProfile]>,
      Array<SwapRequest>,
      Array<[Principal, Principal, Array<Message>]>,
    ]
  >,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessagesWith' : ActorMethod<[Principal], Array<Message>>,
  'getSwapRequests' : ActorMethod<[], Array<SwapRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectSwapRequest' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'sendSwapRequest' : ActorMethod<[Principal], undefined>,
  'verifyProfile' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];